import { createFileRoute } from "@tanstack/react-router";
import { Mail, MapPin, MessageCircle, Phone } from "lucide-react";
import { Button } from "@/components/ui/button";
import { PageHero, SiteLayout } from "@/components/site-layout";
import { absoluteUrl } from "@/lib/site-url";
import { OG_IMAGE } from "@/lib/seo";

export const Route = createFileRoute("/contact")({ head: () => ({ meta: [{ title: "Contact Irrigation Expert Hyderabad" }, { name: "description", content: "Contact our Hyderabad irrigation experts for landscaping, drip irrigation, sprinkler installation, fountains, repairs and annual maintenance." }, { property: "og:title", content: "Contact an Irrigation Expert in Hyderabad" }, { property: "og:description", content: "Plan a landscaping, irrigation or water-management project in Hyderabad and South India." }, { property: "og:url", content: absoluteUrl("/contact") }, { property: "og:image", content: OG_IMAGE }, { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary_large_image" }, { name: "twitter:title", content: "Contact an Irrigation Expert in Hyderabad" }, { name: "twitter:description", content: "Plan a landscaping, irrigation or water-management project in Hyderabad and South India." }, { name: "twitter:image", content: OG_IMAGE }], links: [{ rel: "canonical", href: absoluteUrl("/contact") }], scripts: [{ type: "application/ld+json", children: JSON.stringify({ "@context": "https://schema.org", "@type": "LocalBusiness", name: "Smart Irrigation Design & Consulting", telephone: "+91 94942 30489", email: "smartirrigationdis21@gmail.com", address: { "@type": "PostalAddress", streetAddress: "Flat G6, Galaxy Avenue Apartment, RK I Nagar, Indresham, Patancheru", addressLocality: "Hyderabad", addressRegion: "Telangana", addressCountry: "IN" }, areaServed: ["Hyderabad", "Telangana", "South India"] }) }] }), component: ContactPage });
function ContactPage() { return <SiteLayout><PageHero eyebrow="Start a conversation" title="Tell us what your landscape needs." intro="For new systems, upgrades, technical consulting or annual maintenance, speak directly with our Hyderabad team." /><section className="mx-auto grid max-w-7xl gap-px bg-border border-x border-b border-border md:grid-cols-2"><Contact icon={<Phone />} label="Call" value="+91 94942 30489" href="tel:+919494230489" /><Contact icon={<MessageCircle />} label="WhatsApp" value="Message our team" href="https://wa.me/919494230489?text=Hi%2C%20I%20have%20an%20enquiry%20about%20the%20services" /><Contact icon={<Mail />} label="Email" value="smartirrigationdis21@gmail.com" href="mailto:smartirrigationdis21@gmail.com" /><div className="bg-background p-8 sm:p-12"><MapPin className="size-6 text-accent" /><p className="mt-8 text-[10px] font-bold uppercase tracking-[0.2em] text-muted-foreground">Registered office</p><address className="mt-3 not-italic leading-8">Flat G6, Galaxy Avenue Apartment<br />RK I Nagar, Indresham, Patancheru<br />Hyderabad, Telangana</address></div></section><section className="px-5 py-20 sm:px-8 sm:py-28"><div className="mx-auto max-w-7xl"><div className="max-w-2xl"><p className="text-[10px] font-bold uppercase tracking-[0.3em] text-secondary">Helpful before you call</p><h2 className="mt-5 text-3xl font-semibold sm:text-5xl">A few details help us advise faster.</h2></div><div className="mt-12 grid gap-px bg-border border border-border sm:grid-cols-2 lg:grid-cols-4">{["Site location and approximate area","Landscape or crop type","Available water source and pressure","New system, upgrade or maintenance"].map((item, i) => <div key={item} className="bg-background p-7"><span className="text-xs font-bold text-accent">0{i+1}</span><p className="mt-8 text-sm font-semibold leading-6">{item}</p></div>)}</div></div></section></SiteLayout>; }
function Contact({ icon, label, value, href }: { icon: React.ReactNode; label: string; value: string; href: string }) { return <div className="bg-background p-8 sm:p-12"><span className="text-accent [&_svg]:size-6">{icon}</span><p className="mt-8 text-[10px] font-bold uppercase tracking-[0.2em] text-muted-foreground">{label}</p><p className="mt-3 break-words text-lg font-semibold">{value}</p><Button asChild variant="link" className="mt-6 px-0 text-secondary"><a href={href} target={href.startsWith("http") ? "_blank" : undefined} rel={href.startsWith("http") ? "noreferrer" : undefined}>Open {label.toLowerCase()}</a></Button></div>; }